# Generated by Django 5.0.7 on 2024-07-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=75, verbose_name='Nombre')),
                ('edad_medico', models.IntegerField(verbose_name='Edad')),
                ('sexo_cliente', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='MedicoDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.CharField(max_length=75, verbose_name='Nombre')),
                ('edad_medico', models.IntegerField(verbose_name='Edad')),
                ('especialidad', models.CharField(max_length=50, verbose_name='Especialidad')),
                ('sexo_medico', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
                'db_table': 'Medicos',
            },
        ),
        migrations.CreateModel(
            name='CitaDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_cita_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConsultasCrud.clientedb')),
                ('medico_cita_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConsultasCrud.medicodb')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'Citas',
            },
        ),
    ]
